### ISSUE TITLE
Just the server?

### ISSUE THREAD

**Issue by lostinblue** [icza/gowut#13]
Is this just the server or are you also providing a webkit like client UI?

**Comment by icza** [comment]
This is a "complete" webkit. When you build your UI using components of the gowut library and you start the server, and when clients (browsers) request for the UI pages, the library (server side) will automatically, transparently generate and send the client side code (including HTML, CSS, JS documents).

**Comment by icza** [comment]
Does my previous (edited) comment answers your question?

**Comment by lostinblue** [comment]
Yes it did, sorry I missed the notification earlier. i will try it out again and see if I can get it to work. There is an active 3d engine that seeks to do something similar too, would make sense to combine our efforts.
