### ISSUE TITLE
Expander inquiry

### ISSUE THREAD

**Issue by crisarceramos** [icza/gowut#18]
Hi Dev team,
Thanks for this wonderful golang project. 
I am currently developing a simple dashboard using this project.
However, part of the code needs to loop through objects.
I used Expander and set the content as Table. 
My concern is that, I want to access the Expander content(table) and be able to loop through its components (cells). How can I do that? What is the reverse of Expander.setContent()? 
I am new to golang in general. 
Can you provide a simple code to achieve this? Thanks alot! :)

-Cris

**Comment by crisarceramos** [comment]
got a solution using type assertions. thanks anyways

**Comment by icza** [comment]
`Expander` is an interface, its doc:
https://godoc.org/github.com/icza/gowut/gwu#Expander

It has a method `SetContent()` to set the content, and it has another method `Content()` which returns the content.

`Content()` returns the content as a value of type `Comp` (which is an interface). And yes, if you set a `Table` and you want to use specific methods of `Table`, you need to use type assertion.
