### ISSUE TITLE
Expose http.Request via Event

### ISSUE THREAD

**Issue by icza** [icza/gowut#19]
Brainstorming. Consider exposing the [`http.Request`](https://golang.org/pkg/net/http/#Request) associated with the processing of the [`Event`](https://godoc.org/github.com/icza/gowut/gwu#Event).

It could be useful for informational purposes such as getting client's IP.

Consider not adding it to the `Event` interface, so users won't _"overuse"_ it, but document that the dynamic type of `Event`s may have a method something like `GetRequest()` which could be called after a type assertion.

**Comment by TheSeeker** [comment]
I wanted to use httpauth for login/password management, so I needed the responsewriter and request ... I did add it to the Event interface because I didn't know where else to put it. Here's my hack if you're interested:

[diff.txt](https://github.com/icza/gowut/files/384730/diff.txt)

**Comment by icza** [comment]
Reporting that I implemented this, see commit https://github.com/icza/gowut.dev/commit/36ab65723441a1864976e441523ab3dfd774e3f0 for details.

Request and response are available after a type assertion, for example:

    someButton.AddEHandlerFunc(func(e gwu.Event) {
        if hrr, ok := e.(gwu.HasRequestResponse); ok {
            req := hrr.Request()
            log.Println("Client addr:", req.RemoteAddr)
        }
    }, gwu.ETypeClick)
