### ISSUE TITLE
can not panic() program

### ISSUE THREAD

**Issue by GoogleCodeExporter** [icza/gowut#2]
```
What steps will reproduce the problem?

b := gwu.NewButton("QUIT")
b.AddEHandlerFunc(func(e gwu.Event) {
  panic("try to show goroutines and quit")
}, gwu.ETYPE_CLICK)

What is the expected output? What do you see instead?
I wish there is a method to let me quit program when button pressed

What version of the product are you using? On what operating system?

go 1.1
gowut 6cc150b5189d

Please provide any additional information below.

```

Original issue reported on code.google.com by `dlin...@gmail.com` on 7 Jun 2013 at 8:30

**Comment by icza** [comment]
Event handlers are called from goroutines serving HTTP requests, which are protected by the [`net/http`](https://golang.org/pkg/net/http/) package.

If you want to terminate the application, you can call [`os.Exit()`](https://golang.org/pkg/os/#Exit).
