### ISSUE TITLE
listbox.go deselect error.

### ISSUE THREAD

**Issue by TheSeeker** [icza/gowut#20]
When deselecting all items from a listbox using ctrl+click, the last item deselected remains active despite no longer being highlighted on the list.  This can be demonstrated by going to https://gowut-demo.appspot.com/show and clicking the "ListBox" link on the left, then using ctrl+click to select and deselect items on the list.  sum=? will always equal the last item deselected.

**Comment by icza** [comment]
Closing as fixed by `gowut.dev` [pull request #2](https://github.com/icza/gowut.dev/pull/2).
