### ISSUE TITLE
Forcing component refresh/update without using timer

### ISSUE THREAD

**Issue by crisarceramos** [icza/gowut#22]
Hi dev team,
I am developing a simple monitoring dashboard which updates the values every minute using golang thicker. I would like to know how to refresh/update the gwu component when the thicker is about to execute like below sample code:
`ticker := time.NewTicker(time.Second * 60)`
	`go func() {`
		`for t := range ticker.C {`
			`log.Println(t)`
			`serverCheck() //retrieve values somewhere and set gwu components values`
`//missing line that should update the gwu component in the browser to current value`
		`}`
	`}()`

I know I can do this using gwu.NewTimer and call e.MarkDirty(...). But I instead opt to use golang thicker so that there is no delays when updating the components. 
Can you please suggest, thanks!

**Comment by icza** [comment]
Currently server side notification or event push is not supported by Gowut.

Your best bet is the [`gwu.Timer`](https://godoc.org/github.com/icza/gowut/gwu#Timer) component as you described.

**Comment by crisarceramos** [comment]
thanks icza, i was able to fix it with gwu.Timer dedicated to updating the components if an update is not running.
