### ISSUE TITLE
nil pointer dereference in gwu.Table.Clear() 

### ISSUE THREAD

**Issue by TheSeeker** [icza/gowut#23]
If a table is constructed without all cells being populated, it will display fine, but the lack of cell contents causes a nil pointer dereference when performing a Clear() operation at [table.go+169](https://github.com/icza/gowut/blob/7193576b5008b321eb24f583cc356c6ef8eafde6/gwu/table.go#L169)

Wrapping that line in an if c2 != nil {} solves the problem for me, but I don't know if that's the proper way to address the issue.

**Comment by icza** [comment]
Thanks for reporting, will look into it.

**Comment by icza** [comment]
I somehow forgot about this issue. It is fixed now (on dev branch). Thanks again for reporting it.
