### ISSUE TITLE
Can Session closing generate an event?

### ISSUE THREAD

**Issue by gnewton** [icza/gowut#29]
I use sessions in my application. However, when the session expires, the gui is unresponsive. I would like to update/replace the gui contents when the session expires with a button that says something like "Start again", which starts a new session and presents the starting state of the gui. I have tried a number of things but have not been able to do this.

As the Session.Removed(gwu.Session) does not expose any functions of use (those in Event like Event.ReloadWin(string)) I don't see how I can do this...

Thanks,
Glen

**Comment by icza** [comment]
If a session times out, it is not possible to "restore" it at the server side. Since the server side data (model) is stored in the session, it means when the session "goes", so goes the server side data.

Check out the [`SessMonitor`](https://godoc.org/github.com/icza/gowut/gwu#SessMonitor) component. It can be used to display the remaining session time. You can also see it at the top of the live demo: https://gowut-demo.appspot.com/show

**Comment by gnewton** [comment]
Right. So at session_timout minus 5 seconds, I'd like to replace the entire gui page with a single HTML link "Session expired: click here to restart" which would link to the application url. Suggestions for doing this? :-)   Thanks.

**Comment by icza** [comment]
The `SessMonitor` component uses different style classes in different "phases" of the session timeout:

    // Default style classes: "gwu-SessMonitor", "gwu-SessMonitor-Expired",
    // "gwu-SessMonitor-Error"

You can for example override / extend the `"gwu-SessMonitor-Expired"` CSS class to make it appear as you want it (e.g. masking everything on the page). You can also wrap the `SessMonitor` in a `Link` to make it point to the start page.

You can also set the JavaScript function of the `SessMonitor` component which is responsible to format the session timeout value. This function gets the session timeout in seconds:

    function convertSessTimeout(sec)

In your function you may check the timeout, and perform custom actions according to your needs. Note that by default the `SessMonitor` checks the session (and network connectivity state) once in every 60 seconds, which you may change using the `SetTimeout()` method.
