### ISSUE TITLE
Event handler (ETypeFocus) for panel never actives when tabPanel selects the panel

### ISSUE THREAD

**Issue by willauld** [icza/gowut#30]
I have a Panel in a TabPanel that I want to update went the panel becomes visible. The can occur if its TabPanel's tab is clicked on or when SetSelected() is called. Whenever either of these occur I want to update the panel. Using an event handler for ETypeFocus seems like the correct way to go but does not work. Looking at the code I believe that SetSelected() in TabPanel.go should include code to activate such a handler if present but it does not currently do so.   

If this is the correct direction, I'd be happy to put together a pull request.

**Comment by icza** [comment]
`ETypeFocus` means the component gained focus, which is not guaranteed when a tab is selected. So it is right not to generate a focus event automatically.

Dispatching an event requires an `Event` value which is not available in the `SetSelected()` method, so the `SetSelected()` method and the `TabPanel` component itself cannot do this.

However, from the event handler where you call `SetSelected()`, you do have an `Event`, and you can call its `Event.SetFocusedComp()` method which will focus the specified component after processing the current event, which in turn will trigger an event of type `ETypeFocus`.

Does that solve your problem?

**Comment by willauld** [comment]
Thanks, after I sent the note I also notice this issue with not having an event available in the SetSelected() function. Given this, I implemented your suggestion (or think I did) but I don't see my focus handler being activated. Here is what I did:

         t := gwu.NewTabPanel()
	erl := gwu.NewLabel("Edit Rentals")
	tabc := buildEditRentals(j)
	erl.AddEHandlerFunc(func(e gwu.Event) {
		e.SetFocusedComp(tabc)
	}, gwu.ETypeClick)
	t.Add(erl, tabc)
	
...
func buildEditRentals(j * jawaInfo) gwu.Panel {
...
        c := gwu.NewPanel()
	c.AddEHandlerFunc(func(e gwu.Event) {
		Notify("EditRentals Focus Event happened", e)
	}, gwu.ETypeFocus )
...
       return c
}

In this clicking on the tab containing the label erl does not cause the focus handler to activate and send the Notice. 
It looks like it should work. I must be missing something important.

Thanks,
Will

**Comment by icza** [comment]
I don't think labels are focusable in HTML. You should try some other component, e.g. `Link` which generates an HTML anchor (`<a>`) which are focusable.

**Comment by willauld** [comment]
I have the handler attached to the label (that activates the specific tab panel) call the SetFocusedComp(tabc). Tabc is a panel that contains everything I'm displaying through the specific tab. Sorry I not sure that I am using the terminology correctly. Anyway, I'm not trying to cause a label to receive the focus but rather a panel.

**Comment by icza** [comment]
Yes, I understand that. I recommended the link because I know they surely can be focused. It is equally good if you choose a component in the tab content pane, but that does not necessarily contain focusable components.

**Comment by willauld** [comment]
OK, I switched the SetFocusedComp() to a listbox. Clicking on the list box within the tabPanel activates its focus handler but calling SetFocusedComp(lb) from the tabPanel tab click handler does not cause the lb focus handler to fire. 

I'll continue to look at this to see if this is something I'm doing wrong but I am not seeing it now. Will report back what I find.
Thanks

**Comment by willauld** [comment]
Found the issue. I had two calls to SetFocusedComp() they and one of them was pointing to the panel. 

Thanks so much for you help,
Will
