### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by mg03** [icza/gowut#32]
Im expanding on the login demo. 

1) I have a remote sso service which i call and it returns a token. I need to store that token as a cookie. Any pointers on how to add a cookie to the domain?
2) Once authorized, I present the user with a set of external links. Now when the user clicks the external link, I need to send above token as a cookie to the external link. How do i achieve this?

**Comment by icza** [comment]
Creating / reading cookies involves accessing the `http.Request` and `http.ResponseWriter`.

Gowut hides these under the hood, you work with event handlers. But the request and response is stored and can be extracted from an `Event`. The concrete type that implements `Event` implements [`gwu.HasRequestResponse`](https://godoc.org/github.com/icza/gowut/gwu#HasRequestResponse).

Read its doc which contains an example how it can be used: https://godoc.org/github.com/icza/gowut/gwu#HasRequestResponse
