### ISSUE TITLE
How to update contents of a listbox

### ISSUE THREAD

**Issue by Bl4cksunLtd** [icza/gowut#33]
Is there a way to amend the contents of a listbox during an event called from the same page?
I'd like a refresh button that would rebuild the contents of a listbox based on the current values in a slice on the server.
I can do this with a textbox using tb.SetText(var) followed by marking the tb as dirty but cant work out how to do this for a list box.

I've managed to achieve this by doing a <parent container>.Remove(listbox) then creating a new listbox with the new values, adding it to the parent container then marking the parent container dirty. I could do this as the parent container was a table, but not sure how you would reinsert it into the middle of a normal panel? Adding a SetContents(slice) as a listbox method would make things a lot simpler.

**Comment by icza** [comment]
Good point, `ListBox` should support changing its values. Will add in the next minor version.

**Comment by icza** [comment]
Commit f7f07d3bd2d3595629d4ab1ba96495329e8b0b76 adds `Values()` and `SetValues()` methods to `ListBox`.
