### ISSUE TITLE
Race Condition with login_demo.go

### ISSUE THREAD

**Issue by rhedile** [icza/gowut#35]
Starting with,

sudo go run -race login_demo.go

Then logging in from two separate Clients and then waiting for the sessions to timeout yields the attached log file. 

[racelog.txt](https://github.com/icza/gowut/files/1329149/racelog.txt)

**Comment by icza** [comment]
Fixed this and other data race issues, see https://github.com/icza/gowut/commit/5e87800568eddcd9e251f42190eab0974eed6fab for details on the `dev` branch.

Not yet released to `master`. If you could test, that would be nice.

**Comment by icza** [comment]
Releasing a new 1.3.0 version soon, including this fix.
