### ISSUE TITLE
ETypeMousedown event name not consistent with other event names

### ISSUE THREAD

**Issue by djadala** [icza/gowut#38]
https://github.com/icza/gowut/blob/7dde321edeeb14de3c4f665436fc5a698863cf48/gwu/event.go#L38

Hi,
it should be ETypeMouseDown, in all other event names last word is upper case.

Regards.

**Comment by icza** [comment]
You're right. Unfortunately changing its name would be a backward
incompatible change, so I'll leave it as-is for now.

**Comment by djadala** [comment]
```
const (
	ETypeMouseDown = ETypeMousedown
)
```

**Comment by icza** [comment]
Will add this extra const. Thanks for letting me know.

**Comment by icza** [comment]
Done in the `dev` branch.
