### ISSUE TITLE
make  images undraggable

### ISSUE THREAD

**Issue by djadala** [icza/gowut#39]
https://github.com/icza/gowut/blob/7dde321edeeb14de3c4f665436fc5a698863cf48/gwu/image.go#L52

Hi,
i'm annoyed with dragable images,
is it good idea to make images undraggable ?
```strImgCl = []byte(`" draggable="false">`)```

If not, just close issue and sorry for noise.

Regards

**Comment by icza** [comment]
I wouldn't make all images non-draggable by default.

You can always make yours by setting the `draggable` property to `false`, e.g.:

    img := gwu.NewImage("alt", "source")
    img.SetAttr("draggable", "false")

If you want all your images non-draggable by default, create your own factory function, e.g.:

    func NewImg(text, url string) gwu.Image {
        img := gwu.NewImage("alt", "source")
        img.SetAttr("draggable", "false")
        return img
    }

And use that when creating images.

**Comment by djadala** [comment]
OK, thanks.
