### ISSUE TITLE
Any plans to support webview as a backend?

### ISSUE THREAD

**Issue by SaadHafiane** [icza/gowut#40]
Are there any plans to support [Webview](https://github.com/zserge/webview) as a backend?
This could be a viable alternative to sciter.

**Comment by icza** [comment]
The Gowut server is a standard web server, so there is no reason why it wouldn't work with Webview as-is.

Just start your gowut server as you would normally do, e.g.

    appName, addr := "Gowut example", "localhost:8081"
    server := gwu.NewServer(appName, addr)

And pass the address to `webview.Open()` like this:

    webview.Open(appName, "http://" + addr + "/path/to/window", 800, 600, true)

What support are you expecting to be added?
