### ISSUE TITLE
console logging 

### ISSUE THREAD

**Issue by andrewelkin** [icza/gowut#53]
Fantastic lib, thank you!    

Some of the logging goes directly to the default log implementation, like this:
(https://github.com/icza/gowut/blob/59696fa2ebe7cbdc28af32b5cba2b3a866e70cee/gwu/server_start.go#L57)

I define server's logger so I can control the output. the log.Println just goes where it wants. 

Also, there is a bunch of debug logging not possible to turn off :
here https://github.com/icza/gowut/blob/59696fa2ebe7cbdc28af32b5cba2b3a866e70cee/gwu/server.go#L800

and here https://github.com/icza/gowut/blob/59696fa2ebe7cbdc28af32b5cba2b3a866e70cee/gwu/server.go#L759

**Comment by icza** [comment]
The _"Starting GUI server on"_ message is a one-time message, and if it bothers you, you could "mute" it by directing the default logger to a buffer (or to discard it) (by calling `log.SetOutput()`).

Yes, the other 2 log messages could happen quite often, and currently there's no way to suppress them (except passing / using a `nil` logger).

**Comment by andrewelkin** [comment]
thank you!  I redirected all logging to a wrapper class and filtered to the level I needed.
