### ISSUE TITLE
Private method in RadioGroup

### ISSUE THREAD

**Issue by gganeocase** [icza/gowut#54]
```
// RadioGroup interface defines the group for grouping radio buttons.
type RadioGroup interface {
	// Name returns the name of the radio group.
	Name() string

	// Selected returns the selected radio button of the group.
	Selected() RadioButton

	// PrevSelected returns the radio button that was selected
	// before the current selected radio button.
	PrevSelected() RadioButton

	// setSelected sets the selected radio button of the group,
	// and before that sets the current selected as the prev selected
	setSelected(selected RadioButton)
}
```
In the file [state_buttons.go]

Hi,
Could you tell me why you didn't put your <setSelected> method in public? Is it a deliberate choice or a mistake?
Thx for your good job !

**Comment by icza** [comment]
Likely to prevent / minimize programmer errors. You could pass any button to it, even one that is not in the group.

Note that you can set the selected button of a group by calling `SetState()` method of the button you wish to be selected. This method properly takes care of the button state and the deselection of the currently selected button (if any).

**Comment by gganeocase** [comment]
Ok, I understand your choice, thanks for this quick answer
