### ISSUE TITLE
Local pdf embedding issues

### ISSUE THREAD

**Issue by emerikaji** [icza/gowut#55]
Hi,
I decided to use Gowut for a simple UI I have to make that needs to display a pdf and some input fields, with the goal of refreshing the pdf after changes have been applied.
However, using the `gwu.NewHTML` method with both `object` and `embed` tags, my local pdf never gets loaded. Here is what I tried:
```go
path, err := os.Getwd()
if err != nil {
    log.Fatal(err)
}
gwu.NewHTML("<object data=\"file:///" + path + "/public/out.pdf\" type=\"application/pdf\">")
gwu.NewHTML("<embed src=\"file:///" + path + "/public/out.pdf\" type=\"application/pdf\">")
```
Both elements appear in the source html, but not on the page. Only when I replace the file link with a pdf uploaded online does everything work, and yet the pdf file is accessible on my computer at the exact location in the tags, since if I open that location in my browser it shows up just fine.

For some additional context, this program will only be ran on windows machines.

Is this a problem with Gowut, or am I getting my html wrong? Any help would be appreciated. 
Thank you.

**Comment by icza** [comment]
If the PDF gets displayed with a link pointing to an online PDF, then it's probably some kind of permission issue, not Gowut related.

**Comment by emerikaji** [comment]
I see. Would you perhaps have any idea as to what could be happening, since the pdf is accessible from the very same browser the Gowut web page is opened in? It's especially weird since it seems the pdf file is not even requested from the page. No access denied or not found, just no request.

**Comment by icza** [comment]
I tried this (on Linux) and it works for me. Make sure `path` contains forward slashes and not backslashes. Also make sure to use absolute path.

**Comment by emerikaji** [comment]
Thank you for taking the time to try it for me. I still haven't got it to work, but since this is not a problem with Gowut, I will close the issue.
