### ISSUE TITLE
Calling MarkDirty from a goroutine doesn't have any effect

### ISSUE THREAD

**Issue by emerikaji** [icza/gowut#56]
I'm currently trying to write an Event Handler function such that after the event has triggered and a fixed time period has passed, some code is executed and the affected part of the page is refreshed. Therefore, I tried to use `time.AfterFunc()` inside the event handler, like so:
```go
var timer *time.Timer
textBox := gwu.NewTextBox("")
textBox.AddSyncOnETypes(gwu.ETypeKeyUp)
textBox.AddEHandlerFunc(func(e gwu.Event) {
    if timer != nil {
        if !timer.Stop() {
            <-timer.C
        }
        timer = nil
    }
    timer = time.AfterFunc(3*time.Second, func() {
        // some code affecting a panel
        e.MarkDirty(panel)
        timer = nil
    })
}, gwu.ETypeKeyUp)
```
I checked already that the afterfunc is correctly called after the defined time period using some logs. However, the components are never updated.

This code, that doesn't use the afterfunc call, works:
```go
textBox := gwu.NewTextBox("")
textBox.AddSyncOnETypes(gwu.ETypeKeyUp)
textBox.AddEHandlerFunc(func(e gwu.Event) {
    // some code affecting a panel
    e.MarkDirty(panel)
}, gwu.ETypeKeyUp)
```
Which led me to suspect the fact that `time.AfterFunc()` calls the code in its own goroutine.
Is it possible to call `MarkDirty()` and update components from a goroutine? If not, is there any other way to delay component updates?

Thank you.

**Comment by icza** [comment]
If you change anything on the backend (in a goroutine), the client apps in the browsers won't know about it.

If you want timed events, you may use the [`gwu.Timer`](https://pkg.go.dev/github.com/icza/gowut/gwu#Timer) component: it can generate a timed event or a series of timed events periodically. When such events are generated, it will call back to the server where you can make modifications and use `MarkDirty()` at the end.

**Comment by emerikaji** [comment]
Is `gwu.Timer` used in any examples, or would you have any on hand? This sounds like the right solution overall, but I cannot seem to figure out its usage. This is what I'm currently trying:
```go
var timer = gwu.NewTimer(3 * time.Second)
timer.AddSyncOnETypes(gwu.ETypeStateChange)
timer.AddEHandlerFunc(func(e gwu.Event) {
	e.MarkDirty(panel)
}, gwu.ETypeStateChange)

textBox := gwu.NewTextBox("")
textBox.AddSyncOnETypes(gwu.ETypeKeyUp)
textBox.AddEHandlerFunc(func(e gwu.Event) {
    // some code affecting a panel
    timer.Reset()
    e.MarkDirty(timer)
}, gwu.ETypeKeyUp)
```

**Comment by icza** [comment]
Gowut comes with builtin examples. There's a Showcase of Features example in the `_examples/showcase` folder. That has an examle of almost all Gowut components, including the `Timer`.

Note: you also have to add the `gwu.Timer` component to a client container, else its code won't get included and executed in the browser.

Let me know if you can't make your example working based on the Timer example in the Showcase of Features.

**Comment by icza** [comment]
Note: Gowut was written well before Go modules, but this is how you can try the Showcase of Features with the latest Go version:

```
git clone https://github.com/icza/gowut
cd gowut
go mod init github.com/icza/gowut
go run _examples/showcase/showcase.go
```

This will start Gowut locally and open the Showcase of Features page in your browser automatically. Click on the **Timer** link on the bottom of the left menu to see it in action.

**Comment by emerikaji** [comment]
Thank you very much for your help! The timer method ended up working perfectly for what I needed to do. The variable names in the showcase makes studying the code a little difficult, but the component was intuitive enough for me to figure it out.

Even if this is an old project, I might contribute at some point. Either way, thank you for your work.
